<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3MASFbx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3MASFbx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3MASFbx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3MASFbx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3MASFbx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3MASFbx',
    'container.build_id' => '5ae13e12',
    'container.build_time' => 1644797415,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3MASFbx');
