<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'attraction' => [[], ['_controller' => 'App\\Controller\\AttractionController::index'], [], [['text', '/attraction']], [], []],
    'admin-dashboard/attraction' => [[], ['_controller' => 'App\\Controller\\AttractionController::admin_index'], [], [['text', '/admin-dashboard/attraction']], [], []],
    'blog' => [[], ['_controller' => 'App\\Controller\\BlogController::index'], [], [['text', '/blog']], [], []],
    'admin-dashboard/blog' => [[], ['_controller' => 'App\\Controller\\BlogController::admin_index'], [], [['text', '/admin-dashboard/blog']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], []],
    'excursion' => [[], ['_controller' => 'App\\Controller\\ExcursionController::index'], [], [['text', '/excursion']], [], []],
    'admin-dashboard/excursion' => [[], ['_controller' => 'App\\Controller\\ExcursionController::admin_index'], [], [['text', '/admin-dashboard/excursion']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'admin-dashboard' => [[], ['_controller' => 'App\\Controller\\HomeController::admin_index'], [], [['text', '/admin-dashboard']], [], []],
    'hotel' => [[], ['_controller' => 'App\\Controller\\HotelController::index'], [], [['text', '/hotel']], [], []],
    'admin-dashboard/hotel' => [[], ['_controller' => 'App\\Controller\\HotelController::admin_index'], [], [['text', '/admin-dashboard/hotel']], [], []],
    'maisonhotes' => [[], ['_controller' => 'App\\Controller\\MaisonhotesController::index'], [], [['text', '/maisonhotes']], [], []],
    'admin-dashboard/maisonhotes' => [[], ['_controller' => 'App\\Controller\\MaisonhotesController::admin_index'], [], [['text', '/admin-dashboard/maisonhotes']], [], []],
    'users' => [[], ['_controller' => 'App\\Controller\\UsersController::index'], [], [['text', '/users']], [], []],
    'admin-dashboard/users' => [[], ['_controller' => 'App\\Controller\\UsersController::admin_index'], [], [['text', '/admin-dashboard/users']], [], []],
];
